### ISSUE TITLE
libvsnr2d.dll not found

### ISSUE THREAD

**Issue by sebi06** [pierre-weiss/VSNR_2D-3D_GPU#1]
Hi,

I follow the instructions and the dll is located here

`c:\Users\m1srh\Documents\Fiji\plugins\VSNR\libvsnr2d.dll`

but I always get the error below. Any ideas?

(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52n; Java 1.8.0_66 [64-bit]; Windows 10 10.0; 87MB of 12176MB (<1%)
 
```
java.lang.UnsatisfiedLinkError: Unable to load library 'C:\Users\m1srh\DOCUME~1\Fiji\plugins\VSNR\libvsnr2d.dll': Das angegebene Modul wurde nicht gefunden.

	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:145)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:188)
	at com.sun.jna.Library$Handler.<init>(Library.java:123)
	at com.sun.jna.Native.loadLibrary(Native.java:255)
	at com.sun.jna.Native.loadLibrary(Native.java:241)
	at VSNR_2D.initDll(VSNR_2D.java:404)
	at VSNR_2D.run(VSNR_2D.java:73)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:231)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by pierre-weiss** [comment]
Dear Sebi06,

I haven't done that for a long time actually and I don't use Windows
anymore. Are you sure that the path is exactly the same (including capital
letters) ? I know that this should not be a problem under Windows, but it
is worth a try to have the names matched exactly.

c:\Users\m1srh\Documents\Fiji\plugins\VSNR\libvsnr2d.dll

C:\Users\m1srh\DOCUME~1\Fiji\plugins\VSNR\libvsnr2d.dll

Best,
Pierre

**Comment by ant-Korn** [comment]
Dear @sebi06,

Sorry for late response.
It seems that the error is caused by the fact that these dynamic libraries (libvsnr2d.dll and  	libvsnr3d.dll) are dependent on [CUDA 8.0](https://developer.nvidia.com/cuda-80-ga2-download-archive) and more specifically on cufft64_80.dll and cublas64_80.dll. So, you can install this version of CUDA and the plugin should work.

I hope this may help you.
